### ISSUE TITLE
Error using McsHDF5.McsData with .h5 from MultiChannel DataManager

### ISSUE THREAD

**Issue by colleen-j-brennan** [multichannelsystems/McsMatlabDataTools#2]
I have received the following error message when trying to load an .h5 file generated by the MultiChannel DataManager:

>> data = McsHDF5.McsData('DIV_iLMO7-2_controls.h5');
Error using h5infoc
The filename specified was either not found on the MATLAB path or it contains unsupported characters.

Error in h5info (line 108)
    hinfo = h5infoc(filename,location, useUtf8);

Error in McsHDF5.McsData (line 63)
                inf = h5info(filename);

I have made sure the file is in the path.

**Comment by armwal** [comment]
Hi, which Matlab version and which version of the McsMatlabDataTools are you using? Does this only happen for one specific file or  for others as well?

**Comment by colleen-j-brennan** [comment]
MATLAB version R2020a update 4 (9.8.0.1418392) - 64 bit (online course use).

McsMatlabDataTools version 1.3.0.

It's only happening to one of my files.

**Comment by armwal** [comment]
If it is just a single file, could you try whether a reexport of the recording to HDF5 via the Multi Channel DataManager helps? This error message from h5info is unfortunately not very specific and will also occur if the file is not a valid HDF5 file or damaged in some way.

If the same error happens for the new exported file, I'll need to have a look at the HDF5 file itself and maybe also at the original recording to see if there is a bug with the HDF5 export process. I can provide you with an upload option, if necessary.

**Comment by colleen-j-brennan** [comment]
A reexport worked. Thank you so much for your help.
